kind: Run
type: docker-run
name: seed-votes
description: |
  Seed Postgres with some test data. We don't use the seed service in the compose project here, but reference
  an image from a `container` Build instead.
dependencies: [deploy.vote]
spec:
  projectName: vote
  image: ${actions.build.seed-votes.outputs.deployment-image-id}
  networks: ["front-tier"]

---

kind: Deploy
disabled: ${environment.name == "local"}
name: vote
type: exec

---

kind: Run
type: docker-compose-exec
name: clear-db
dependencies: [deploy.db]
spec:
  service: db
  projectName: vote
  command: [psql, -U, "${var.db.username}", -d, "${var.db.dbName}", "-c", "TRUNCATE VOTES"]

---
# kind: Run
# type: docker-compose-run
# name: seed-votes
# dependencies: [deploy.vote]
# spec:
#   service: seed # From the Compose stack

# ---

apiVersion: garden.io/v1
kind: Project
name: vote
environments:
  - name: local
    variables:
      db:
        username: postgres
        dbName: postgres
      # db: vote.local.demo.garden
  # - name: remote
  #   variables:
  #     baseHostname: ${project.name}-testing-${var.userId}.dev-1.sys.garden
providers:
  - name: docker-compose
    environments: [local]
    # projects: [{ path: "." }]
  # - name: local-kubernetes
  #   environments: [local]
  # - name: kubernetes
  #   environments: [remote]
  #   # Replace the below values as appropriate
  #   context: gke_garden-ci_europe-west1-b_core-ci
  #   namespace: ${project.name}-testing-${var.userId}
  #   defaultHostname: ${var.baseHostname}
  #   buildMode: kaniko
  #   deploymentRegistry:
  #     hostname: eu.gcr.io    # <- set this according to the region your cluster runs in
  #     namespace: garden-ci   # <- set this to the project ID of the target cluster
  #   imagePullSecrets:
  #     # Make sure this matches the name and namespace of the imagePullSecret you've created
  #     # to authenticate with your registry (if needed)
  #     - name: gcr-config
  #       namespace: default
variables:
  userId: ${local.username}
  # postgres-database: postgres
  # # Only use for testing!
  # postgres-username: postgres
  # postgres-password: test-password
